# Generated by Django 4.0.4 on 2022-07-02 15:15

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=200)),
                ('analysis', models.CharField(max_length=200)),
                ('lim', models.IntegerField(default=0)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('df_info', picklefield.fields.PickledObjectField(default='5', editable=False)),
            ],
        ),
    ]
